name: NuGet Publish

on:
  push:
    branches:
      - master
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore Kei.Base/Kei.Base.sln

      - name: Build solution
        run: dotnet build Kei.Base/Kei.Base.sln --configuration Release --no-restore

      - name: Pack NuGet packages
        run: |
          dotnet pack Kei.Base/Kei.Base.csproj -c Release -o ./artifacts
          dotnet pack Kei.Base.Domain/Kei.Base.Domain.csproj -c Release -o ./artifacts
          dotnet pack Kei.Base.Extensions/Kei.Base.Extensions.csproj -c Release -o ./artifacts
          dotnet pack Kei.Base.Helper/Kei.Base.Helper.csproj -c Release -o ./artifacts

      - name: Publish to NuGet
        if: startsWith(github.ref, 'refs/tags/v')
        run: dotnet nuget push ./artifacts/*.nupkg \
          --api-key ${{ secrets.NUGET_API_KEY }} \
          --source https://api.nuget.org/v3/index.json
